[terminal]
shell = "/usr/bin/tmux"

[window]
dynamic_padding = true
opacity = 1.0
resize_increments= true

[font]
normal = {family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
size = 14
offset = {x = 0, y = 0}
